/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppPage: typeof import('./src/components/app-page/app-page.vue')['default']
    AppTabbar: typeof import('./src/components/app-tabbar/app-tabbar.vue')['default']
    CustomNavbar: typeof import('./src/components/custom-navbar/custom-navbar.vue')['default']
    UAvatar: typeof import('uview-pro/components/u-avatar/u-avatar.vue')['default']
    UBadge: typeof import('uview-pro/components/u-badge/u-badge.vue')['default']
    UCheckbox: typeof import('uview-pro/components/u-checkbox/u-checkbox.vue')['default']
    UColumnNotice: typeof import('uview-pro/components/u-column-notice/u-column-notice.vue')['default']
    UConfigProvider: typeof import('uview-pro/components/u-config-provider/u-config-provider.vue')['default']
    UIcon: typeof import('uview-pro/components/u-icon/u-icon.vue')['default']
    ULoading: typeof import('uview-pro/components/u-loading/u-loading.vue')['default']
    UMask: typeof import('uview-pro/components/u-mask/u-mask.vue')['default']
    UNoticeBar: typeof import('uview-pro/components/u-notice-bar/u-notice-bar.vue')['default']
    URowNotice: typeof import('uview-pro/components/u-row-notice/u-row-notice.vue')['default']
    USwiper: typeof import('uview-pro/components/u-swiper/u-swiper.vue')['default']
    USwitch: typeof import('uview-pro/components/u-switch/u-switch.vue')['default']
    UTabbar: typeof import('uview-pro/components/u-tabbar/u-tabbar.vue')['default']
    UToast: typeof import('uview-pro/components/u-toast/u-toast.vue')['default']
    UTransition: typeof import('uview-pro/components/u-transition/u-transition.vue')['default']
  }
}
